import Head from "next/head"
import type { NextPage } from "next"
import {useRouter} from "next/router"

import {FormEvent} from "react"

import AuthPage from "@/authPage/AuthPage"
import {useAuth} from "../contexts/AuthProvider"

import styles from "@/styles/Auth.module.scss"

const Login: NextPage = () => {
  const {login} = useAuth()
  const router = useRouter()

  const form = {
    inputList: [
      { id: 'email',
        type: 'email',
        placeholder: 'name@work-email.com'
      },
      { id: 'pwd',
        type: 'password',
        placeholder: 'Enter your password'
      }
    ],
    btnLabel: 'Login',
    onSubmit: async(e: FormEvent) => {
      e.preventDefault()
      const target = e.target as HTMLFormElement

      const email = target.email.value
      const pwd = target.pwd.value

      const res = await login(email, pwd)
      if (res.status === 200)
        router.push("/client")
    }
  }

  return (
    <div className={styles.authPage}>
      <Head>
        <title>Login | Slack</title>
        <meta 
          name="description" 
          content="Generated by create next app" />
        <link rel="icon" href="/slack.ico" />
      </Head>
      <AuthPage
        form={form}
        link="/register"
        title="Sign in to Slack"
        linkLabel="Create an account"
        description="We suggest using email address you use at work."
      />
    </div>
  )
}

export default Login
