import Head from "next/head"
import type {NextPage} from "next"
import {useRouter} from "next/router"

import {FormEvent} from "react"

import AuthPage from "@/authPage/AuthPage"
import {useAuth} from "../contexts/AuthProvider"

import styles from "@/styles/Auth.module.scss"

const Register: NextPage = () => {
  const {register} = useAuth()
  const router = useRouter()

  const form = {
    btnLabel: 'Register',
    inputList: [
      { id: 'email',
        type: 'email',
        placeholder: 'name@work-email.com'
      },
      { id: 'pwd',
        type: 'password',
        placeholder: 'Enter your password'
      },
      {
        id: 'confirmPwd',
        type: 'password',
        placeholder: 'Confirm password'
      }
    ],
    onSubmit: async(e: FormEvent) => {
      e.preventDefault()
      const target = e.target as HTMLFormElement

      const email = target.email.value
      const pwd = target.pwd.value
      const confirmPwd = target.confirmPwd.value

      const res = await register(email, pwd, confirmPwd)
      if (res.status === 200)
        router.push("/client")
    }
  }

  return (
    <div className={styles.authPage}>
      <Head>
        <title>Register | Slack</title>
        <meta 
          name="description" 
          content="Generated by create next app" />
        <link rel="icon" href="/slack.ico" />
      </Head>
      <AuthPage
        form={form}
        link="/login"
        title="Join Slack"
        linkLabel="I have an account"
        description="We suggest using email address you use at work."
      />
    </div>
  )
}

export default Register
